FROM nginx:alpine
COPY index.html /usr/share/nginx/html/
COPY robots.txt /usr/share/nginx/html/
COPY css/ /usr/share/nginx/html/css/
COPY js/ /usr/share/nginx/html/js/
COPY admin/ /usr/share/nginx/html/admin/
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY proxy_pass.conf /etc/nginx/proxy_pass.conf
