import os
from flask import Flask, jsonify, request, session
from flask_cors import CORS
import mysql.connector
from mysql.connector import pooling

app = Flask(__name__)
# Secret is generated by setup.sh and provided through FLASK_SECRET
app.secret_key = os.environ.get("FLASK_SECRET") or os.urandom(32)

app.config.update(
    SESSION_COOKIE_NAME="mollies_session",
    SESSION_COOKIE_HTTPONLY=False, # Set to False so JS can see it if needed for debugging
    SESSION_COOKIE_SAMESITE="Lax",
    SESSION_COOKIE_SECURE=False, 
    PERMANENT_SESSION_LIFETIME=60 * 60 * 24
)
CORS(app, supports_credentials=True)

DB_CONFIG = {
    "host": os.environ.get("DB_HOST", "db"),
    "database": os.environ.get("DB_NAME", "mollies_guide"),
    "user": os.environ.get("DB_USER", "mollies"),
    "password": os.environ.get("DB_PASSWORD", ""),
    "pool_name": "mollies_pool",
    "pool_size": 15,
}

_pool = None
def get_conn():
    global _pool
    if _pool is None: _pool = pooling.MySQLConnectionPool(**DB_CONFIG)
    return _pool.get_connection()

@app.route("/login", methods=["POST"])
def login():
    session.permanent = True
    session["authenticated"] = True
    return jsonify({"ok": True})

# Adding multiple common names for the auth check route
@app.route("/auth-check")
@app.route("/auth/check")
@app.route("/status")
@app.route("/verify")
def auth_check():
    if session.get("authenticated"):
        return jsonify({"authenticated": True, "ok": True, "status": "logged_in"})
    return jsonify({"authenticated": False, "ok": False}), 401

@app.route("/categories")
def get_categories():
    conn = get_conn()
    try:
        cur = conn.cursor(dictionary=True)
        cur.execute("SELECT * FROM categories ORDER BY id")
        res = cur.fetchall()
        cur.close()
        return jsonify(res)
    finally:
        conn.close()

@app.route("/crops/distinct")
def get_distinct_crops():
    conn = get_conn()
    try:
        cur = conn.cursor(dictionary=True)
        cur.execute("SELECT name, COUNT(DISTINCT location_id) as farm_count FROM crops GROUP BY name ORDER BY name")
        res = cur.fetchall()
        cur.close()
        return jsonify(res)
    finally:
        conn.close()

@app.route("/locations")
def get_locations():
    cat = request.args.get("category")
    month = request.args.get("month", type=int)
    crop = request.args.get("crop", "").strip().lower()
    conn = get_conn()
    try:
        cur = conn.cursor(dictionary=True)
        where, params = [], []
        if cat:
            cats = [c.strip() for c in cat.split(",")]
            where.append(f"c.name IN ({','.join(['%s']*len(cats))})")
            params.extend(cats)
        if month:
            loc_m = "(%s BETWEEN l.season_start_month AND l.season_end_month OR (l.season_start_month > l.season_end_month AND (%s >= l.season_start_month OR %s <= l.season_end_month)))"
            crop_m = "EXISTS (SELECT 1 FROM crops cr WHERE cr.location_id = l.id AND (%s BETWEEN cr.season_start_month AND cr.season_end_month OR (cr.season_start_month > cr.season_end_month AND (%s >= cr.season_start_month OR %s <= cr.season_end_month))))"
            where.append(f"({loc_m} OR {crop_m})")
            params.extend([month]*6)
        if crop:
            where.append("(EXISTS (SELECT 1 FROM crops cr WHERE cr.location_id = l.id AND LOWER(cr.name) LIKE %s) OR l.county = %s)")
            params.extend([f"%{crop}%", crop])
        wc = " WHERE " + " AND ".join(where) if where else ""
        sql = f"SELECT l.*, c.name AS category, c.color AS category_color FROM locations l LEFT JOIN categories c ON l.category_id = c.id {wc}"
        cur.execute(sql, params)
        res = cur.fetchall()
        cur.close()
        return jsonify(res)
    finally:
        conn.close()

@app.route("/locations/<int:loc_id>", methods=["GET"])
def get_location(loc_id):
    conn = get_conn()
    try:
        cur = conn.cursor(dictionary=True)
        cur.execute("SELECT l.*, c.name AS category FROM locations l LEFT JOIN categories c ON l.category_id = c.id WHERE l.id = %s", (loc_id,))
        loc = cur.fetchone()
        if loc:
            cur.execute("SELECT * FROM crops WHERE location_id = %s", (loc_id,))
            loc["crops"] = cur.fetchall()
        cur.close()
        return jsonify(loc)
    finally:
        conn.close()

@app.route("/locations/<int:loc_id>", methods=["PUT"])
def update_location(loc_id):
    data = request.get_json() or {}
    conn = get_conn()
    try:
        cur = conn.cursor()
        sql = """
            UPDATE locations SET 
            name = %s, address = %s, city = %s, zip = %s, phone = %s, 
            website = %s, hours = %s, notes = %s, category_id = %s,
            event_date = %s, county = %s, 
            season_start_month = %s, season_end_month = %s
            WHERE id = %s
        """
        params = (
            data.get('name'), data.get('address'), data.get('city'), data.get('zip'), 
            data.get('phone'), data.get('website'), data.get('hours'), data.get('notes'),
            data.get('category_id'), data.get('event_date'), data.get('county'),
            data.get('season_start_month'), data.get('season_end_month'), loc_id
        )
        cur.execute(sql, params)
        conn.commit()
        cur.close()
        return jsonify({"ok": True})
    finally:
        conn.close()

@app.route("/locations/<int:loc_id>/notes", methods=["GET"])
def get_notes(loc_id):
    conn = get_conn()
    try:
        cur = conn.cursor(dictionary=True)
        cur.execute("SELECT * FROM notes WHERE location_id = %s ORDER BY created_at DESC", (loc_id,))
        res = cur.fetchall()
        cur.close()
        return jsonify(res)
    finally:
        conn.close()

@app.route("/locations/<int:loc_id>/notes", methods=["POST"])
def add_note(loc_id):
    data = request.get_json() or {}
    note = data.get("note", "").strip()
    if not note: return jsonify({"error": "empty note"}), 400
    conn = get_conn()
    try:
        cur = conn.cursor()
        cur.execute("INSERT INTO notes (location_id, note) VALUES (%s, %s)", (loc_id, note))
        conn.commit()
        cur.close()
        return jsonify({"ok": True})
    finally:
        conn.close()

@app.route("/locations/<int:loc_id>/notes/<int:note_id>", methods=["DELETE"])
def delete_note(loc_id, note_id):
    conn = get_conn()
    try:
        cur = conn.cursor()
        cur.execute("DELETE FROM notes WHERE id = %s AND location_id = %s", (note_id, loc_id))
        conn.commit()
        cur.close()
        return jsonify({"ok": True})
    finally:
        conn.close()

@app.route("/counties")
def get_counties():
    conn = get_conn()
    try:
        cur = conn.cursor()
        cur.execute("SELECT DISTINCT county FROM locations WHERE county IS NOT NULL AND county != '' ORDER BY county")
        res = [r[0] for r in cur.fetchall()]
        cur.close()
        return jsonify(res)
    finally:
        conn.close()

@app.route("/locations", methods=["POST"])
def create_location():
    data = request.get_json() or {}
    conn = get_conn()
    try:
        cur = conn.cursor()
        sql = '''
            INSERT INTO locations (name, address, city, zip, phone, website, hours, notes, category_id, event_date, county, season_start_month, season_end_month)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        '''
        params = (
            data.get('name'), data.get('address'), data.get('city'), data.get('zip'), 
            data.get('phone'), data.get('website'), data.get('hours'), data.get('notes'),
            data.get('category_id'), data.get('event_date'), data.get('county'),
            data.get('season_start_month'), data.get('season_end_month')
        )
        cur.execute(sql, params)
        new_id = cur.lastrowid
        conn.commit()
        cur.close()
        return jsonify({"ok": True, "id": new_id})
    finally:
        conn.close()

@app.route("/locations/<int:loc_id>", methods=["DELETE"])
def delete_location(loc_id):
    conn = get_conn()
    try:
        cur = conn.cursor()
        cur.execute("DELETE FROM locations WHERE id = %s", (loc_id,))
        conn.commit()
        cur.close()
        return jsonify({"ok": True})
    finally:
        conn.close()

@app.route("/locations/<int:loc_id>/crops", methods=["POST"])
def add_loc_crop(loc_id):
    data = request.get_json() or {}
    conn = get_conn()
    try:
        cur = conn.cursor()
        cur.execute("INSERT INTO crops (location_id, name, is_pyo, season_start_month, season_end_month) VALUES (%s, %s, %s, %s, %s)",
            (loc_id, data.get('name'), data.get('is_pyo'), data.get('season_start_month'), data.get('season_end_month')))
        conn.commit()
        cur.close()
        return jsonify({"ok": True})
    finally:
        conn.close()

@app.route("/crops/<int:crop_id>", methods=["PUT"])
def update_loc_crop(crop_id):
    data = request.get_json() or {}
    conn = get_conn()
    try:
        cur = conn.cursor()
        cur.execute("UPDATE crops SET name=%s, is_pyo=%s, season_start_month=%s, season_end_month=%s WHERE id=%s",
            (data.get('name'), data.get('is_pyo'), data.get('season_start_month'), data.get('season_end_month'), crop_id))
        conn.commit()
        cur.close()
        return jsonify({"ok": True})
    finally:
        conn.close()

@app.route("/crops/<int:crop_id>", methods=["DELETE"])
def delete_loc_crop(crop_id):
    conn = get_conn()
    try:
        cur = conn.cursor()
        cur.execute("DELETE FROM crops WHERE id = %s", (crop_id,))
        conn.commit()
        cur.close()
        return jsonify({"ok": True})
    finally:
        conn.close()

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)
